export const SET_AUTH = 'SET_AUTH'; 
export const SET_SELLER_PRODUCT = 'SET_SELLER_PRODUCT'; 
export const SET_USHOP_PRODUCT = 'SET_USHOP_PRODUCT'; 
export const DELETE_SELLER_PRODUCT = 'DELETE_SELLER_PRODUCT'; 